# Generated by Django 4.1 on 2022-09-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0007_payment_status_payment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
